apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-provider-gcp
spec:
  projectID: 
  credentials:
    source: Secret
    secretRef:
      namespace: 
      name: gcp-account-creds
      key: credentials
